# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQ1p-5OpIgsJv69EF-nW9DETn0Z7D743
"""

def addition(a,b):
  return a+b
def subtract(a,b):
  return a-b
def mul(a,b):
  return a*b